spring:
  application:
    name: micro-api-data-client-feign
    
server:
  port: 8383
  
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      
feign:
  client:
    config:
      feignName:
        connectTimeout: 60000
        readTimeout: 60000            