spring:
  application:
    name: micro-api-data-config-client
      
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    
server:
  port: 8040
  
           