#日志配置
logging:
  level:
    root: info
    com.xrj.springcloud.variousapidata: debug
  path: F:\\log\\various-api-data
  
#redis config
spring:
  redis:
    host: 192.168.36.111
    port: 6379
    pool:
      max-active: 16
      max-wait: -1
      max-idle: 16
    timeout: 0 
    
#spring cloud config
  application:
    name: micro-various-api-data-weather-data

eureka:
  client:
    ##设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    service-url: 
      defaultZone : http://localhost:8761/eureka/         