#日志配置
logging:
  level:
    root: info
    com.xrj.springcloud.variousapidata: debug
  path: F:\\log\\various-api-data
  
#redis config
spring:
  redis:
    host: 192.168.36.111
    port: 6379
    pool:
      max-active: 16
      max-wait: -1
      max-idle: 16
    timeout: 0      