#日志配置
logging:
  level:
    root: info
    com.xrj.springcloud.variousapidata: debug
  path: F:\\log\\various-api-data
  
#spring cloud config
spring:
  application:
    name: micro-various-api-data-weather-city-eureka-feign

eureka:
  client:
    ##设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    service-url: 
      defaultZone : http://localhost:8761/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 6000
        readTimeout: 6000          