spring:
  application:
    name: micro-api-data-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waylau/spring-cloud-microservices-development
          search-paths:
          - config-repo
#          username: crixue@qq.com
#          password: xue13581321  

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    
server:
  port: 8040
  
           